name: aws test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  start:
    name: Start ec2 instance
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Start instance
      env:
        aws-instance-id: ${{ secrets.AWS_INSTANCE_ID }}
      run: aws ec2 start-instances --instance-ids ${aws-instance-id}

  work:
    name: Run tests
    runs-on: ubuntu-20.04

    steps:
    - name: Sleep
      run: sleep 300

  stop:
    name: Stop ec2 instance
    runs-on: ubuntu-20.04

    steps:
    - name: Stop instance
      env:
        aws-instance-id: ${{ secrets.AWS_INSTANCE_ID }}
      run: aws ec2 stop-instances --instance-ids ${aws-instance-id}
